### ISSUE TITLE
Fails to build with boost >= 1.87.0

### ISSUE THREAD

**Issue by berolinux** [EttusResearch/uhd#821]
## Issue Description ##
uhd host libs fail to build with boost >= 1.87.0 (1.86 is ok) due to the removal of previously deprecated functions

## Setup Details ##
OpenMandriva Lx Cooker or any other OS with boost 1.87.0 or higher

## Expected Behavior ##
compiles

## Actual Behaviour ##
fails to compile

## Steps to reproduce the problem ##
1. Update to boost 1.87.0
2. Try to build uhd

## Additional Information ##
Here's a partial patch that fixes the obvious issues that have a straight forward replacement.
[uhd-boost-1.87.0.patch.txt](https://github.com/user-attachments/files/18132930/uhd-boost-1.87.0.patch.txt)

It's not a complete fix though, after fixing these issues it gets to another problem.
```
/home/bero/abf/uhd/BUILD/uhd-4.7.0.0-build/uhd-4.7.0.0/host/lib/deps/rpclib/lib/rpc/client.cc:159:18: error: no matching member function for call to 'resolve'
  159 |         resolver.resolve({pimpl->addr_, std::to_string(pimpl->port_)});
      |         ~~~~~~~~~^~~~~~~
```
and
```
/home/bero/abf/uhd/BUILD/uhd-4.7.0.0-build/uhd-4.7.0.0/host/lib/deps/rpclib/lib/rpc/client.cc:44:21: error: no type named 'iterator' in 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>'; did you mean 'std::_Bit_const_iterator::iterator'?
   44 |     void do_connect(tcp::resolver::iterator endpoint_iterator) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                     std::_Bit_const_iterator::iterator
```
Not sure how to fix those right now.

**Comment by mbr0wn** [comment]
@berolinux you must have just missed the updates -- e75629c3cfb4d0a654648f775e65e79375cf4f13 and adfe953d965e58b5931c1b1968899492c8087cf6 takes care of this.
