### ISSUE TITLE
uhd does not build with libgpsd 3.18 or newer

### ISSUE THREAD

**Issue by asy972** [EttusResearch/uhd#303]
## Issue Description ##
uhd (include commit 0408f47b23, Prepare branch for upcoming UHD 3.15 release) does not build with libgpsd 3.18 or newer:

host/lib/usrp/gpsd_iface.cpp:122:40: error: too few arguments to function 'int gps_read(gps_data_t*, char*, int)'

**Comment by asy972** [comment]
I apologize. It's my inattention. I mixed sources.
